name: cycle_partner
description: Cycle Partner application.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cycle_core_domain:
    path: ../../packages/core_domain
  cycle_permissions:
    path: ../../packages/permissions
  cycle_sharing:
    path: ../../packages/sharing

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
