name: cycle_doctor
description: Cycle Doctor application.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cycle_core_domain:
    path: ../../packages/core_domain
  cycle_clinical_copilot:
    path: ../../packages/clinical_copilot

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
