name: cycle_patient
description: Cycle Patient application.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  cycle_core_domain:
    path: ../../packages/core_domain
  cycle_crypto:
    path: ../../packages/crypto
  cycle_storage:
    path: ../../packages/storage
  cycle_storage_sqlcipher:
    path: ../../packages/storage_sqlcipher
  cycle_secure_key_store:
    path: ../../packages/secure_key_store

flutter:
  uses-material-design: true
