name: cycle_patient
description: Cycle Patient application.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  cycle_core_domain:
    path: ../../packages/core_domain
  cycle_crypto:
    path: ../../packages/crypto
  cycle_health_ingestion:
    path: ../../packages/health_ingestion
  cycle_security:
    path: ../../packages/security
  cycle_storage:
    path: ../../packages/storage
  cycle_storage_file_vault:
    path: ../../packages/storage_file_vault
  cycle_storage_sqlcipher:
    path: ../../packages/storage_sqlcipher
  cycle_secure_key_store:
    path: ../../packages/secure_key_store
  local_auth: ^3.0.2
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
